# Sidebar navigation

- label: 'Overview'
  link: '/'
- label: 'Register and Get API keys'
  link: '/getting-started/register'
- label: Recieve Payments
  items:
    - label: 'Ways to Receive Payments'
      link: '/R-Payments/remita-inline'
    # - label: 'Navigation'
    #   link: '/usage/navigation'
    # - label: 'Shadowing'
    #   link: '/usage/shadowing'
- label: Make Payments
  items:
    - label: 'Ways to Make Payments'
      link: '/M-Payments/make-payments'